# Generated by Django 4.2.2 on 2023-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionAnswer', '0002_like_answer_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='unlikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
